version: '3'
services:
    postgres:
        build:
            context: .
            dockerfile: Dockerfile
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: puzzle
        ports:
            - "5432:5432"
